[phases.setup]
aptPkgs = ["libglib2.0-0", "libgl1", "libsm6", "libxext6", "libxrender1"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "pip install --force-reinstall --no-deps opencv-python-headless>=4.9.0",
]
